#pragma once
#include "sdk.h"

namespace SDK
{
    struct LiftButtonFields // Generated by ida pro
    {
        MonoBehaviourFields monoBehaviourFields;
        Animator* anim;
        PhotonView* view;
        void* photonInteract;
        void* source;
        ExitLevel* exitLevel;
        void* truckRamp;
        float timer;
        bool isAnimation;
        bool isClosed;
        char pad0[2];
        Collider* wallCollider;
        bool canClose;
        bool isSingleUse;
        bool hasUsed;
        char pad1[5];
    };

	struct LiftButton
	{
		void* Clazz;
		void* Monitor;
		LiftButtonFields Fields;
	};

	DEC_MET(LiftButton_Update, void(*)(LiftButton* liftButton, MethodInfo* methodInfo), "Assembly-CSharp", "", "LiftButton", "Update", 0);
	DEC_MET(LiftButton_AttemptUse, void(*)(LiftButton* liftButton, void* photonMessageInfo, MethodInfo* methodInfo), "Assembly-CSharp", "", "LiftButton", "AttemptUse", 1);
	DEC_PATTERN_INSTR(Call_WaitForSeconds, L"GameAssembly.dll", "il2cpp", "E8 ? ? ? ? 48 8D 4F ? 48 89 5F ? 48 8B D3 E8 ? ? ? ? 48 8B 5C 24 ? B0 ? C7 47 ? ? ? ? ? 48 83 C4 ? 5F C3 83 F9 ? 75 ? C7 47 ? ? ? ? ? 48 85 C0 74 ? 88 48 ? 32 C0 48 83 C4 ? 5F C3 E8 ? ? ? ? ? ? ? ? ? 40 53 48 83 EC ? 48 8D 0D ? ? ? ? E8 ? ? ? ? 48 8B C8 E8 ? ? ? ? 33 D2 48 8B C8 48 8B D8 E8 ? ? ? ? 48 8D 0D ? ? ? ? E8 ? ? ? ? 48 8B D0 48 8B CB E8 ? ? ? ? ? ? 48 83 EC"); // Address LiftButton.MoveNext + 0x61 || FIND: call    UnityEngine_WaitForSeconds$$_ctor
}